apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: MachineDeployment
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: edge01-control-plane
spec:
  clusterName: openstack-nephio
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: openstack-nephio-md-0
      clusterName: openstack-nephio
      failureDomain: DX-G
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: openstack-nephio-md-0
      version: v1.30.0