# permissions for end users to view ktclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: ktcluster-viewer-role
rules:
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktclusters/status
  verbs:
  - get
