# permissions for end users to view ktmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: ktmachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktmachinetemplates/status
  verbs:
  - get
