# permissions for end users to view ktnetworkfirewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: ktnetworkfirewall-viewer-role
rules:
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktnetworkfirewalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktnetworkfirewalls/status
  verbs:
  - get
