# permissions for end users to edit ktsubjecttokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: ktsubjecttoken-editor-role
rules:
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktsubjecttokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - ktsubjecttokens/status
  verbs:
  - get
