---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - clusters
  - ktclusters
  - ktmachinetemplates
  - kubeadmconfigtemplates
  - kubeadmcontrolplanes
  - machinedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - clusters/finalizers
  - ktclusters/finalizers
  - ktmachinetemplates/finalizers
  - kubeadmconfigtemplates/finalizers
  - kubeadmcontrolplanes/finalizers
  - machinedeployments/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.dcnlab.ssu.ac.kr
  resources:
  - clusters/status
  - ktclusters/status
  - ktmachinetemplates/status
  - kubeadmconfigtemplates/status
  - kubeadmcontrolplanes/status
  - machinedeployments/status
  verbs:
  - get
  - patch
  - update
